TestShop/Web/Controllers/HallController.cs
using AutoMapper;
using BusinessLogic.LogicBusiness.Hall;
using BusinessLogic.LogicBusiness.Movie;
using BusinessLogic.LogicBusiness.Session;
using DataAccess.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using Web.Models;

namespace Web.Controllers
{
    public class HallController : Controller
    {
        IMapper mapper;
        IHallLogic hallLogic;

        public HallController(IMapper mapper, IHallLogic hallLogic)
        {
            this.hallLogic = hallLogic;
            this.mapper = mapper;

        }

        [Route("Hall/GetHallsByCinema/{idCinema}")]
        public IActionResult GetHallsByCinema(long idCinema)//1
        {
            List<HallModel> halls = hallLogic.GetHallByIdCinema(idCinema);
            var hallsUI = mapper.Map<List<HallUI>>(halls);

            return View(hallsUI);
        }

        [HttpGet]
        [Route("Hall/GetHallByMovie/{idCinema}")]
        public IActionResult GetHallByMovie(long idCinema)//1
        {
            long idMovie = Convert.ToInt64(HttpContext.Session.GetString("idMovie"));
            List<HallModel> halls = hallLogic.GetHallByIdMovie(idMovie,idCinema);
            var hallsUI = mapper.Map<List<HallUI>>(halls);

            return View(hallsUI);
        }

        [Route("Hall/GetHall/{idHall}")]
        public IActionResult GetHall(long idHall, long idSession)//1
        {
            HttpContext.Session.SetString("idSession", idSession.ToString());
            HallModel hall = hallLogic.GetHall(idHall);
            var hallUI = mapper.Map<HallUI>(hall);

            return View(hallUI);
        }

        //[HttpGet]
        //[Route("Hall/SelectHallForMovie/{idMoive}")]
        //public IActionResult SelectHallForMovie(long idMovie)
        //{
        //    HttpContext.Session.SetString("idMovieForCinema", idMovie.ToString());
        //    long idCinema = Convert.ToInt64(HttpContext.Session.GetString("idCinemaForMovie"));
        //    List<HallModel> halls = hallLogic.GetHallByIdCinema(idCinema);
        //    var hallsUI = mapper.Map<List<HallUI>>(halls);

        //    return View(hallsUI);
        //}
    }
}

TestShop/Web/Controllers/HomeController.cs
using AutoMapper;
using BusinessLogic.LogicBusiness.Cinema;
using BusinessLogic.LogicBusiness.Movie;
using DataAccess.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using Web.Models;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        ICinemaLogic cLogic;
        IMovieLogic mLogic;
        IMapper mapper;

        public HomeController(ICinemaLogic cLogic, IMovieLogic mLogic, IMapper mapper)
        {
            this.cLogic = cLogic;
            this.mLogic = mLogic;
            this.mapper = mapper;
        }

        public IActionResult Index()
        {
            List<CinemaModel> cinemas = cLogic.GetCinemas();
            var cinemasUI = mapper.Map<List<CinemaUI>>(cinemas);
            return View(cinemasUI);
        }

        [Route("Home/GetAllMoviesForCinema/{idCinema}")]
        public IActionResult GetAllMoviesForCinema(long idCinema)
        {
            HttpContext.Session.SetString("idCinemaForMovie", idCinema.ToString());
            List<MovieSessionModel> movies = mLogic.GetMoviesWithCinema(idCinema);
            var moviesUI = mapper.Map<List<MovieSessionModelUI>>(movies);
            return View(moviesUI);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestShop/Web/Views/Home/GetAllMoviesForCinema.cshtml
@using Microsoft.AspNetCore.Http
@model IEnumerable<DataAccess.Models.MovieSessionModelUI>

@{
    ViewData["Title"] = "GetAllMoviesForCinema";
}

<h1>GetAllMoviesForCinema</h1>

@if(Context.Session.GetString("loginUser") == "Admin")
{
    <p>
        <a asp-controller="Hall" asp-action="GetHallsByCinema" asp-route-id="@Context.Session.GetString("idCinemaForMovie")">Add new film</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Discription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Time)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>                   
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Discription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Time)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>

                    @Html.HiddenFor(modelItem => item.IdSession)
                    @Html.HiddenFor(modelItem => item.IdMovie)
                    @Html.HiddenFor(modelItem => item.IdHall)
                    <td>
                        @Html.ActionLink("See halls", "GetHall","Hall", new {  id=item.IdHall, idSession = item.IdSession })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}else
{
   <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Discription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Time)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>                   
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Discription)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Time)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Price)
                    </td>

                    @Html.HiddenFor(modelItem => item.IdSession)
                    @Html.HiddenFor(modelItem => item.IdMovie)
                    @Html.HiddenFor(modelItem => item.IdHall)
                    <td>
                        @Html.ActionLink("See halls", "GetHall","Hall", new {  id=item.IdHall, idSession = item.IdSession })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

TestShop/Web/Views/Home/Index.cshtml
@model IEnumerable<CinemaUI>

@{
    ViewData["Title"] = "Index";
}

<table class="table">
    <thead>
        <h1>All cinemas in city</h1>

    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <h1>@Html.DisplayFor(modelItem => item.Name)</h1>
                </td>
                <td>
                    <img src="@Html.DisplayFor(modelItem => item.Picture)" width="200" height="200">
                </td>
                @Html.HiddenFor(modelItem => item.Id)
                <td>
                    @Html.ActionLink("All films in this cinema", "GetAllMoviesForCinema", new {  id=item.Id  })
                </td>
            </tr>
        }
    </tbody>
</table>