TestShop/Web/Controllers/AreaController.cs
using AutoMapper;
using BusinessLogic.LogicBusiness.Area;
using DataAccess.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using Web.Models;

namespace Web.Controllers
{
    public class AreaController : Controller
    {
        IAreaLogic areaLogic;
        IMapper mapper;

        public AreaController(IMapper mapper, IAreaLogic areaLogic)
        {
            this.areaLogic = areaLogic;
            this.mapper = mapper;
        }

        [Route("Area/GetAreasByIdHall/{idHall}")]
        public IActionResult GetAreasByIdHall(long idHall)
        {
            List<AreaModel> areas = areaLogic.GetFKHall(idHall);
            var areasUI = mapper.Map<List<AreaUI>>(areas);

            return View(areasUI);
        }
    }
}

TestShop/Web/Controllers/HallController.cs
using AutoMapper;
using BusinessLogic.LogicBusiness.Hall;
using BusinessLogic.LogicBusiness.Movie;
using BusinessLogic.LogicBusiness.Session;
using DataAccess.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using Web.Models;

namespace Web.Controllers
{
    public class HallController : Controller
    {
        IMapper mapper;
        IHallLogic hallLogic;

        public HallController(IMapper mapper, IHallLogic hallLogic)
        {
            this.hallLogic = hallLogic;
            this.mapper = mapper;

        }

        [Route("Hall/GetHallsByCinema/{idCinema}")]
        public IActionResult GetHallsByCinema(long idCinema)//1
        {
            List<HallModel> halls = hallLogic.GetHallByIdCinema(idCinema);
            var hallsUI = mapper.Map<List<HallUI>>(halls);

            return View(hallsUI);
        }

        [HttpGet]
        [Route("Hall/GetHallByMovie/{idCinema}")]
        public IActionResult GetHallByMovie(long idCinema)//1
        {
            long idMovie = Convert.ToInt64(HttpContext.Session.GetString("idMovie"));
            List<HallModel> halls = hallLogic.GetHallByIdMovie(idMovie,idCinema);
            var hallsUI = mapper.Map<List<HallUI>>(halls);

            return View(hallsUI);
        }

        [Route("Hall/GetHall/{idHall}")]
        public IActionResult GetHall(long idHall, long idSession)//1
        {
            HttpContext.Session.SetString("idSession", idSession.ToString());
            HallModel hall = hallLogic.GetHall(idHall);
            var hallUI = mapper.Map<HallUI>(hall);

            return View(hallUI);
        }

        //[HttpGet]
        //[Route("Hall/SelectHallForMovie/{idMoive}")]
        //public IActionResult SelectHallForMovie(long idMovie)
        //{
        //    HttpContext.Session.SetString("idMovieForCinema", idMovie.ToString());
        //    long idCinema = Convert.ToInt64(HttpContext.Session.GetString("idCinemaForMovie"));
        //    List<HallModel> halls = hallLogic.GetHallByIdCinema(idCinema);
        //    var hallsUI = mapper.Map<List<HallUI>>(halls);

        //    return View(hallsUI);
        //}
    }
}

TestShop/Web/Controllers/MovieController.cs
using AutoMapper;
using BusinessLogic.LogicBusiness.Movie;
using BusinessLogic.LogicBusiness.Session;
using DataAccess.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using Web.Models;

namespace Web.Controllers
{
    public class MovieController : Controller
    {
        ISessionLogic sessionlogic;
        IMapper mapper;
        IMovieLogic movieLogic;

        public MovieController(IMapper mapper, ISessionLogic session, IMovieLogic movieLogic)
        {
            this.sessionlogic = session;
            this.mapper = mapper;
            this.movieLogic = movieLogic;
        }

        [HttpGet]
        public IActionResult GetAllMovies()
        {
            List<MovieSessionModel> movies = sessionlogic.GetAllSessionsAndMovies();
            var moviesUI = mapper.Map<List<MovieSessionModelUI>>(movies);

            return View(moviesUI);
        }

        [HttpGet]
        [Route("Movie/GetOnlyMovieWithoutSession/{idHall}")]
        public IActionResult GetOnlyMovieWithoutSession(long idHall)
        {
            HttpContext.Session.SetString("idHall", idHall.ToString());
            List<MovieModel> movies = movieLogic.GetMovies();
            var moviesUI = mapper.Map<List<MovieUI>>(movies);

            return View(moviesUI);
        }

        [HttpGet]
        public IActionResult AddNewMovie()
        {
            HttpContext.Request.Headers.TryGetValue("Referer", out var headerValue);
            HttpContext.Session.SetString("redirectURL", headerValue[0]);
            return View();
        }

        [HttpPost]
        public IActionResult AddNewMovie(string name, string discription, DateTime time)
        {
            movieLogic.AddMovie(name, discription, time);
            return Redirect(HttpContext.Session.GetString("redirectURL"));
        }


    }
}

TestShop/Web/Views/Hall/GetHall.cshtml
@using Microsoft.AspNetCore.Http
@model Web.Models.HallUI

@{
    ViewData["Title"] = "GetHall";
}

<h1>GetHall</h1>
@if (Context.Session.GetString("loginUser") == "Admin")
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IdCinema)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Model.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.IdCinema)
                </td>
                <td>
                    @Html.ActionLink("See areas", "GetAreasByIdHall", "Area", new {  id=Model.Id })
                </td>
            </tr>

        </tbody>
    </table>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IdCinema)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => Model.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => Model.IdCinema)
                </td>
                <td>
                    @Html.ActionLink("See areas", "GetAreasByIdHall", "Area", new {  id=Model.Id })
                </td>
            </tr>

        </tbody>
    </table>

}

TestShop/Web/Views/Hall/GetHallByMovie.cshtml
@model IEnumerable<Web.Models.HallUI>

@{
    ViewData["Title"] = "GetHallByMovie";
}

<h1>GetHallByMovie</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                <div>NUmber Hall</div><br/>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
                @Html.HiddenFor(modelItem => item.IdCinema)            
            <td>
                @Html.ActionLink("See areas", "GetAreasByIdHall", "Area", new {  id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

TestShop/Web/Views/Hall/GetHallsByCinema.cshtml
@using Microsoft.AspNetCore.Http
@model IEnumerable<HallUI>

@{
    ViewData["Title"] = "GetHallsByCinema";
}

<h1>All halls in this cinema</h1>

@if (Context.Session.GetString("loginUser") == "Admin")
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    Number hall
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    @Html.HiddenFor(modelItem => item.IdCinema)
                    <td>
                        @Html.ActionLink("See movie", "GetOnlyMovieWithoutSession", "Movie", new {  id=item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}else
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    Number hall
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Id)
                    </td>
                    @Html.HiddenFor(modelItem => item.IdCinema)
                    <td>
                        @Html.ActionLink("See areas", "GetAreasByIdHall", "Area", new {  id=item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

TestShop/Web/Views/Hall/SelectHallForMovie.cshtml
@model IEnumerable<Web.Models.HallUI>

@{
    ViewData["Title"] = "SelectHallForMovie";
}

<h1>SelectHallForMovie</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdCinema)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdCinema)
            </td>
            <td>
                    @Html.ActionLink("AddMovieForCinema", "Session", new {  id=item.Id  }) 
            </td>
        </tr>
}
    </tbody>
</table>