TestShop/Web/Controllers/AreaController.cs
using AutoMapper;
using BusinessLogic.LogicBusiness.Area;
using DataAccess.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.Collections.Generic;
using Web.Models;

namespace Web.Controllers
{
    public class AreaController : Controller
    {
        IAreaLogic areaLogic;
        IMapper mapper;

        public AreaController(IMapper mapper, IAreaLogic areaLogic)
        {
            this.areaLogic = areaLogic;
            this.mapper = mapper;
        }

        [Route("Area/GetAreasByIdHall/{idHall}")]
        public IActionResult GetAreasByIdHall(long idHall)
        {
            List<AreaModel> areas = areaLogic.GetFKHall(idHall);
            var areasUI = mapper.Map<List<AreaUI>>(areas);

            return View(areasUI);
        }
    }
}

TestShop/Web/Controllers/RowController.cs
using AutoMapper;
using BusinessLogic.LogicBusiness.Place;
using BusinessLogic.LogicBusiness.Row;
using DataAccess.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Threading;
using Web.Models;

namespace Web.Controllers
{
    public class RowController : Controller
    {
        IRowLogic rowLogic;
        IPlaceLogic placeLogic;
        IMapper mapper;

        public RowController(IRowLogic rowLogic, IPlaceLogic placeLogic, IMapper mapper)
        {
            this.rowLogic = rowLogic;
            this.placeLogic = placeLogic;
            this.mapper = mapper;
        }

        [Route("Row/GetAllRowsAndPlaces/{idArea}")]
        public IActionResult GetAllRowsAndPlaces(long idArea)
        {
            List<RowUI> rowUI = new List<RowUI>();
            List<RowModel> rows = rowLogic.GetAreaFromRow(idArea);
            string idSession = HttpContext.Session.GetString("idSession");
            long sessionId = Convert.ToInt64(idSession);

            for (int i = 0; i < rows.Count; i++)
            {
                List<PlaceModel> places = placeLogic.GetPlacesBySession(rows[i].Id, sessionId);
                List<PlaceUI> placesUi = mapper.Map<List<PlaceUI>>(places);

                rowUI.Add(new RowUI(rows[i].NumberRow, placesUi));
            }


            return View(rowUI);
        }
    }
}

TestShop/Web/Views/Area/GetAreasByIdHall.cshtml
@model IEnumerable<AreaUI>

@{
    ViewData["Title"] = "GetAreasByIdHall";
}

<h1>All areas in this hall</h1>

<table class="table">
	<thead>
		<tr>
			<th>
				Number area
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(modelItem => item.Id)
				</td>				
				@Html.HiddenFor(modelItem => item.IdHall)
				<td>
					@Html.ActionLink("See places", "GetAllRowsAndPlaces","Row", new {  id=item.Id }) 
					@*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
					@Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
				</td>
			</tr>
		}
	</tbody>
</table>