TestShop/Web/Controllers/PlaceController.cs
using AutoMapper;
using BusinessLogic.LogicBusiness.PlaceSession;
using BusinessLogic.LogicBusiness.ResultChek;
using DataAccess.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using Web.Models;

namespace Web.Controllers
{
    public class PlaceController : Controller
    {
        IPlaceSessionLogic placeSession;
        IGetResultCheckLogic check;
        IMapper mapper;

        public PlaceController(IPlaceSessionLogic placeSession, IGetResultCheckLogic check, IMapper mapper)
        {
            this.placeSession = placeSession;
            this.check = check;
            this.mapper = mapper;
        }

        [HttpGet]
        [Route("Place/PriceByPlaces/{idPlace}")]
        public IActionResult PriceByPlaces(long idPlace)
        {
            long idSession = Convert.ToInt64(HttpContext.Session.GetString("idSession"));
            long idUser = Convert.ToInt64(HttpContext.Session.GetString("idUser"));

            if (idUser <= 0)
            {
                return RedirectToAction("LogIn", "User");
            }
            placeSession.AddPlaceSession(idPlace, idSession, idUser, StatePlace.Book);

            List<Check> checks = check.GetCheck(idUser);
            List<CheckUI> checkUIs = mapper.Map<List<CheckUI>>(checks);

            return View(checkUIs);
        }

        [HttpGet]
        public IActionResult ResultCheck()
        {
            return View();
        }
    }
}

TestShop/Web/Views/Place/PriceByPlaces.cshtml
@model IEnumerable<Web.Models.CheckUI>

@{
    ViewData["Title"] = "PriceByPlaces";
}

<h1>Your Check(`s)</h1>


<table class="table">    
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    <div>Name Movie</div><br>
                @Html.DisplayFor(modelItem => item.NameMovie)<br>
            </td>
            <td>
                    <div>Time Session</div><br>
                @Html.DisplayFor(modelItem => item.TimeSession)
            </td>
            <td>
                    <div>Number Place</div><br>
                    @Html.DisplayFor(modelItem => item.NumberPlace)<br>
            </td>
            <td>
                    <div>Number Row</div><br>
                    @Html.DisplayFor(modelItem => item.NumberRow)<br>
            </td>
            <td>
                    <div>Name Cinema</div><br>
                    @Html.DisplayFor(modelItem => item.NameCinema)<br>
            </td>  
            <td>
                    <div>Price</div><br>
                    @Html.DisplayFor(modelItem => item.Price)<br>
            </td>
        </tr>
        }           @Html.ActionLink("Pay", "ResultCheck", "Place") 
    </tbody>
</table>

TestShop/Web/Views/Place/ResultCheck.cshtml
@{
    ViewData["Title"] = "ResultCheck";
}

<h1>Thank you</h1>